import { CabinetSettings, Patient, Session } from '../types';

export const INITIAL_SETTINGS: CabinetSettings = {
  nomCabinet: "Cabinet d'orthophonie Belgaied Maroua",
  praticien: 'Maroua Belgaied',
  specialite: 'Orthophoniste diplômée - Rééducation du langage & communication',
  tarifConventionne: 35, // DT par séance 45 min
  tarifNonConventionne: 50, // DT par séance 45 min
  heureDebutJournee: '08:30',
  heureFinJournee: '18:00',
  pauseMidiDebut: '12:15',
  pauseMidiFin: '14:00',
  devise: 'DT',
  telephoneCabinet: '+216 71 890 123',
};

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-1',
    nom: 'Amine Ben Salem',
    telephone: '+216 98 450 123',
    isConventionne: true,
    assuranceDetails: 'CNAM - Filière Privée (Prise en charge 100%)',
    numeroAssurance: 'CNAM-04829103',
    dateNaissance: '2019-04-12',
    age: 7,
    pathologie: 'Retard de langage oral & troubles phonologiques',
    notes: 'Enfant très coopératif, progrès notables sur les fricatives.',
    status: 'actif',
    dateCreation: '2026-01-15',
  },
  {
    id: 'pat-2',
    nom: 'Yasmine Trabelsi',
    telephone: '+216 22 341 890',
    isConventionne: true,
    assuranceDetails: 'CNAM - Filière Publique (Conventionnée)',
    numeroAssurance: 'CNAM-11029481',
    dateNaissance: '2017-09-25',
    age: 9,
    pathologie: 'Dyslexie-Dysorthographie mixte',
    notes: 'Travail spécifique sur la voie d’adressage et segmentation syllabique.',
    status: 'actif',
    dateCreation: '2026-02-10',
  },
  {
    id: 'pat-3',
    nom: 'Rayan Chahed',
    telephone: '+216 55 678 912',
    isConventionne: false,
    assuranceDetails: 'Sans convention (Régime privé)',
    dateNaissance: '2021-03-05',
    age: 5,
    pathologie: 'Trouble articulatoire (zézaiement & chuotement)',
    notes: 'Rééducation motrice linguale et praxies bucco-faciales.',
    status: 'actif',
    dateCreation: '2026-03-01',
  },
  {
    id: 'pat-4',
    nom: 'Nour Bouazizi',
    telephone: '+216 97 812 345',
    isConventionne: true,
    assuranceDetails: 'CNAM - Médecin de famille',
    numeroAssurance: 'CNAM-99238410',
    dateNaissance: '2015-11-18',
    age: 11,
    pathologie: 'Bégaiement développemental persistant',
    notes: 'Exercices de fluence, souffle et désensibilisation émotionnelle.',
    status: 'actif',
    dateCreation: '2026-01-20',
  },
  {
    id: 'pat-5',
    nom: 'Mohamed Aziz Khemir',
    telephone: '+216 29 123 789',
    isConventionne: true,
    assuranceDetails: 'CNAM - Filière Privée',
    numeroAssurance: 'CNAM-77382910',
    dateNaissance: '2018-06-30',
    age: 8,
    pathologie: 'Dysphasie développementale réceptive',
    notes: 'Appui sur supports visuels pictogrammes PECS et gestes Borel-Maisonny.',
    status: 'actif',
    dateCreation: '2026-02-22',
  },
  {
    id: 'pat-6',
    nom: 'Eya Mezghani',
    telephone: '+216 50 234 567',
    isConventionne: false,
    assuranceDetails: 'Assurance Complémentaire Privée (Star Assurances)',
    dateNaissance: '2020-08-14',
    age: 6,
    pathologie: 'Déglutition atypique & ventilation buccale',
    notes: 'Coordination avec orthodontiste pour placement pointe de langue.',
    status: 'actif',
    dateCreation: '2026-04-05',
  },
  {
    id: 'pat-7',
    nom: 'Khalil Dridi',
    telephone: '+216 93 456 781',
    isConventionne: true,
    assuranceDetails: 'CNAM - Filière Publique',
    numeroAssurance: 'CNAM-33445566',
    dateNaissance: '2012-10-03',
    age: 14,
    pathologie: 'Trouble complexe du langage écrit',
    notes: 'Préparation examens collège, stratégies de compréhension de texte.',
    status: 'actif',
    dateCreation: '2026-01-10',
  },
  {
    id: 'pat-8',
    nom: 'Salma Gharbi',
    telephone: '+216 26 998 877',
    isConventionne: false,
    assuranceDetails: 'Sans convention (Régime privé direct)',
    dateNaissance: '2022-01-19',
    age: 4,
    pathologie: 'Retard simple du langage oral',
    notes: 'Guidance parentale active et stimulation lexicale par le jeu.',
    status: 'actif',
    dateCreation: '2026-05-12',
  },
  {
    id: 'pat-9',
    nom: 'Adem Riahi',
    telephone: '+216 99 332 211',
    isConventionne: true,
    assuranceDetails: 'CNAM - Filière Privée',
    numeroAssurance: 'CNAM-88192039',
    dateNaissance: '2016-07-08',
    age: 10,
    pathologie: 'Dyspraxie verbale & difficultés graphomotrices',
    notes: 'Rythme syllabique régulé au métronome, très bonne motivation.',
    status: 'actif',
    dateCreation: '2026-02-18',
  },
  {
    id: 'pat-10',
    nom: 'Kenza Mansour',
    telephone: '+216 54 112 233',
    isConventionne: true,
    assuranceDetails: 'CNAM - Régime Général',
    numeroAssurance: 'CNAM-55667788',
    dateNaissance: '2019-12-02',
    age: 7,
    pathologie: 'Dyslexie phonologique débutante',
    notes: 'Entraînement de la conscience phonologique et segmentation.',
    status: 'actif',
    dateCreation: '2026-06-01',
  },
  {
    id: 'pat-11',
    nom: 'Omar Sellami',
    telephone: '+216 98 777 666',
    isConventionne: false,
    assuranceDetails: 'Assurance Groupe Entreprise (Non-conventionné)',
    dateNaissance: '1994-05-14',
    age: 32,
    pathologie: 'Dysphonie dysfonctionnelle & forçage vocal (Enseignant)',
    notes: 'Rééducation de la posture vocale, accolement cordal et souffle abdominal.',
    status: 'actif',
    dateCreation: '2026-07-02',
  },
  {
    id: 'pat-12',
    nom: 'Mariem Jaziri',
    telephone: '+216 23 445 566',
    isConventionne: true,
    assuranceDetails: 'CNAM - Filière Privée',
    numeroAssurance: 'CNAM-44112233',
    dateNaissance: '2014-02-28',
    age: 12,
    pathologie: 'Dyscalculie & dysorthographie grammaticale',
    notes: 'Accord en genre et nombre, morphologie dérivationnelle.',
    status: 'actif',
    dateCreation: '2026-03-14',
  },
];

export const INITIAL_SESSIONS: Session[] = [
  // Lundi 28 Septembre 2026
  {
    id: 'ses-101',
    patientId: 'pat-1',
    patientNom: 'Amine Ben Salem',
    date: '2026-09-28',
    startTime: '08:30',
    endTime: '09:15',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
    motif: 'Rééducation articulation & langage',
    notesSeance: 'Exercices fricatives /s/ et /ch/. Excellents efforts.',
  },
  {
    id: 'ses-102',
    patientId: 'pat-2',
    patientNom: 'Yasmine Trabelsi',
    date: '2026-09-28',
    startTime: '09:15',
    endTime: '10:00',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
    motif: 'Rééducation langage écrit',
    notesSeance: 'Lecture de pseudomots et graphies complexes.',
  },
  {
    id: 'ses-103',
    patientId: 'pat-3',
    patientNom: 'Rayan Chahed',
    date: '2026-09-28',
    startTime: '10:45',
    endTime: '11:30',
    durationMinutes: 45,
    isConventionne: false,
    status: 'realisee',
    tarif: 50,
    motif: 'Praxies bucco-linguo-faciales',
    notesSeance: 'Travail tonus lingual avec abaisse-langue.',
  },
  {
    id: 'ses-104',
    patientId: 'pat-4',
    patientNom: 'Nour Bouazizi',
    date: '2026-09-28',
    startTime: '14:00',
    endTime: '14:45',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
    motif: 'Fluence verbale',
    notesSeance: 'Technique des prolongations douces.',
  },
  {
    id: 'ses-105',
    patientId: 'pat-6',
    patientNom: 'Eya Mezghani',
    date: '2026-09-28',
    startTime: '15:30',
    endTime: '16:15',
    durationMinutes: 45,
    isConventionne: false,
    status: 'realisee',
    tarif: 50,
    motif: 'Déglutition & ventilation',
    notesSeance: 'Exercices mastication et position de repos.',
  },

  // Mardi 29 Septembre 2026 (Aujourd'hui)
  {
    id: 'ses-201',
    patientId: 'pat-5',
    patientNom: 'Mohamed Aziz Khemir',
    date: '2026-09-29',
    startTime: '08:30',
    endTime: '09:15',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
    motif: 'Séance dysphasie',
    notesSeance: 'Compréhension syntaxique des phrases complexes.',
  },
  {
    id: 'ses-202',
    patientId: 'pat-7',
    patientNom: 'Khalil Dridi',
    date: '2026-09-29',
    startTime: '09:15',
    endTime: '10:00',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
    motif: 'Orthographe lexicale',
    notesSeance: 'Mémorisation des règles d’accord.',
  },
  {
    id: 'ses-203',
    patientId: 'pat-8',
    patientNom: 'Salma Gharbi',
    date: '2026-09-29',
    startTime: '10:00',
    endTime: '10:45',
    durationMinutes: 45,
    isConventionne: false,
    status: 'realisee',
    tarif: 50,
    motif: 'Stimulation lexicale précoce',
    notesSeance: 'Jeu symbolique avec figurines dinette.',
  },
  {
    id: 'ses-204',
    patientId: 'pat-9',
    patientNom: 'Adem Riahi',
    date: '2026-09-29',
    startTime: '11:30',
    endTime: '12:15',
    durationMinutes: 45,
    isConventionne: true,
    status: 'planifiee',
    tarif: 35,
    motif: 'Praxies & séquençage oral',
  },
  {
    id: 'ses-205',
    patientId: 'pat-11',
    patientNom: 'Omar Sellami',
    date: '2026-09-29',
    startTime: '14:00',
    endTime: '14:45',
    durationMinutes: 45,
    isConventionne: false,
    status: 'planifiee',
    tarif: 50,
    motif: 'Rééducation de la voix parlée',
  },
  {
    id: 'ses-206',
    patientId: 'pat-10',
    patientNom: 'Kenza Mansour',
    date: '2026-09-29',
    startTime: '15:30',
    endTime: '16:15',
    durationMinutes: 45,
    isConventionne: true,
    status: 'planifiee',
    tarif: 35,
    motif: 'Conscience phonologique',
  },
  {
    id: 'ses-207',
    patientId: 'pat-12',
    patientNom: 'Mariem Jaziri',
    date: '2026-09-29',
    startTime: '16:15',
    endTime: '17:00',
    durationMinutes: 45,
    isConventionne: true,
    status: 'planifiee',
    tarif: 35,
    motif: 'Morphosyntaxe & accords',
  },

  // Mercredi 30 Septembre 2026
  {
    id: 'ses-301',
    patientId: 'pat-1',
    patientNom: 'Amine Ben Salem',
    date: '2026-09-30',
    startTime: '08:30',
    endTime: '09:15',
    durationMinutes: 45,
    isConventionne: true,
    status: 'planifiee',
    tarif: 35,
    motif: 'Rééducation hebdomadaire 2/2',
  },
  {
    id: 'ses-302',
    patientId: 'pat-3',
    patientNom: 'Rayan Chahed',
    date: '2026-09-30',
    startTime: '09:15',
    endTime: '10:00',
    durationMinutes: 45,
    isConventionne: false,
    status: 'planifiee',
    tarif: 50,
    motif: 'Correction articulatoire',
  },
  {
    id: 'ses-303',
    patientId: 'pat-2',
    patientNom: 'Yasmine Trabelsi',
    date: '2026-09-30',
    startTime: '10:45',
    endTime: '11:30',
    durationMinutes: 45,
    isConventionne: true,
    status: 'planifiee',
    tarif: 35,
    motif: 'Vitesse de lecture et fluence',
  },
  {
    id: 'ses-304',
    patientId: 'pat-6',
    patientNom: 'Eya Mezghani',
    date: '2026-09-30',
    startTime: '14:00',
    endTime: '14:45',
    durationMinutes: 45,
    isConventionne: false,
    status: 'planifiee',
    tarif: 50,
    motif: 'Déglutition & praxies',
  },
  {
    id: 'ses-305',
    patientId: 'pat-4',
    patientNom: 'Nour Bouazizi',
    date: '2026-09-30',
    startTime: '14:45',
    endTime: '15:30',
    durationMinutes: 45,
    isConventionne: true,
    status: 'planifiee',
    tarif: 35,
    motif: 'Fluence & prise de parole',
  },

  // Jeudi 01 Octobre 2026
  {
    id: 'ses-401',
    patientId: 'pat-5',
    patientNom: 'Mohamed Aziz Khemir',
    date: '2026-10-01',
    startTime: '09:15',
    endTime: '10:00',
    durationMinutes: 45,
    isConventionne: true,
    status: 'planifiee',
    tarif: 35,
    motif: 'Séance dysphasie',
  },
  {
    id: 'ses-402',
    patientId: 'pat-7',
    patientNom: 'Khalil Dridi',
    date: '2026-10-01',
    startTime: '10:45',
    endTime: '11:30',
    durationMinutes: 45,
    isConventionne: true,
    status: 'planifiee',
    tarif: 35,
    motif: 'Langage écrit & dictée aménagée',
  },
  {
    id: 'ses-403',
    patientId: 'pat-8',
    patientNom: 'Salma Gharbi',
    date: '2026-10-01',
    startTime: '14:00',
    endTime: '14:45',
    durationMinutes: 45,
    isConventionne: false,
    status: 'planifiee',
    tarif: 50,
    motif: 'Langage oral préscolaire',
  },
  {
    id: 'ses-404',
    patientId: 'pat-11',
    patientNom: 'Omar Sellami',
    date: '2026-10-01',
    startTime: '15:30',
    endTime: '16:15',
    durationMinutes: 45,
    isConventionne: false,
    status: 'planifiee',
    tarif: 50,
    motif: 'Voix & résonance',
  },

  // Vendredi 02 Octobre 2026
  {
    id: 'ses-501',
    patientId: 'pat-9',
    patientNom: 'Adem Riahi',
    date: '2026-10-02',
    startTime: '08:30',
    endTime: '09:15',
    durationMinutes: 45,
    isConventionne: true,
    status: 'planifiee',
    tarif: 35,
    motif: 'Dyspraxie & praxies orofaciales',
  },
  {
    id: 'ses-502',
    patientId: 'pat-10',
    patientNom: 'Kenza Mansour',
    date: '2026-10-02',
    startTime: '10:00',
    endTime: '10:45',
    durationMinutes: 45,
    isConventionne: true,
    status: 'planifiee',
    tarif: 35,
    motif: 'Lecture & phonologie',
  },
  {
    id: 'ses-503',
    patientId: 'pat-3',
    patientNom: 'Rayan Chahed',
    date: '2026-10-02',
    startTime: '11:30',
    endTime: '12:15',
    durationMinutes: 45,
    isConventionne: false,
    status: 'planifiee',
    tarif: 50,
    motif: 'Articulation & automatisation',
  },
  {
    id: 'ses-504',
    patientId: 'pat-12',
    patientNom: 'Mariem Jaziri',
    date: '2026-10-02',
    startTime: '14:45',
    endTime: '15:30',
    durationMinutes: 45,
    isConventionne: true,
    status: 'planifiee',
    tarif: 35,
    motif: 'Bilan d’évolution trimestriel',
  },

  // Samedi 03 Octobre 2026
  {
    id: 'ses-601',
    patientId: 'pat-1',
    patientNom: 'Amine Ben Salem',
    date: '2026-10-03',
    startTime: '09:15',
    endTime: '10:00',
    durationMinutes: 45,
    isConventionne: true,
    status: 'planifiee',
    tarif: 35,
    motif: 'Séance de consolidation',
  },
  {
    id: 'ses-602',
    patientId: 'pat-4',
    patientNom: 'Nour Bouazizi',
    date: '2026-10-03',
    startTime: '10:00',
    endTime: '10:45',
    durationMinutes: 45,
    isConventionne: true,
    status: 'planifiee',
    tarif: 35,
    motif: 'Entretien parents et enfant',
  },
  {
    id: 'ses-603',
    patientId: 'pat-6',
    patientNom: 'Eya Mezghani',
    date: '2026-10-03',
    startTime: '10:45',
    endTime: '11:30',
    durationMinutes: 45,
    isConventionne: false,
    status: 'planifiee',
    tarif: 50,
    motif: 'Déglutition & praxies',
  },

  // Données historiques antérieures de Septembre 2026 (Semaines passées)
  // Semaine du 21 au 26 Septembre
  {
    id: 'ses-prev-1',
    patientId: 'pat-1',
    patientNom: 'Amine Ben Salem',
    date: '2026-09-21',
    startTime: '08:30',
    endTime: '09:15',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
    notesSeance: 'Bilan initial de début d’année.',
  },
  {
    id: 'ses-prev-2',
    patientId: 'pat-2',
    patientNom: 'Yasmine Trabelsi',
    date: '2026-09-21',
    startTime: '09:15',
    endTime: '10:00',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
  },
  {
    id: 'ses-prev-3',
    patientId: 'pat-3',
    patientNom: 'Rayan Chahed',
    date: '2026-09-21',
    startTime: '10:45',
    endTime: '11:30',
    durationMinutes: 45,
    isConventionne: false,
    status: 'realisee',
    tarif: 50,
  },
  {
    id: 'ses-prev-4',
    patientId: 'pat-4',
    patientNom: 'Nour Bouazizi',
    date: '2026-09-22',
    startTime: '14:00',
    endTime: '14:45',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
  },
  {
    id: 'ses-prev-5',
    patientId: 'pat-5',
    patientNom: 'Mohamed Aziz Khemir',
    date: '2026-09-22',
    startTime: '08:30',
    endTime: '09:15',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
  },
  {
    id: 'ses-prev-6',
    patientId: 'pat-6',
    patientNom: 'Eya Mezghani',
    date: '2026-09-23',
    startTime: '14:00',
    endTime: '14:45',
    durationMinutes: 45,
    isConventionne: false,
    status: 'realisee',
    tarif: 50,
  },
  {
    id: 'ses-prev-7',
    patientId: 'pat-7',
    patientNom: 'Khalil Dridi',
    date: '2026-09-23',
    startTime: '09:15',
    endTime: '10:00',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
  },
  {
    id: 'ses-prev-8',
    patientId: 'pat-8',
    patientNom: 'Salma Gharbi',
    date: '2026-09-24',
    startTime: '14:00',
    endTime: '14:45',
    durationMinutes: 45,
    isConventionne: false,
    status: 'absent',
    tarif: 50,
    notesSeance: 'Absent pour cause de fièvre.',
  },
  {
    id: 'ses-prev-9',
    patientId: 'pat-9',
    patientNom: 'Adem Riahi',
    date: '2026-09-24',
    startTime: '11:30',
    endTime: '12:15',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
  },
  {
    id: 'ses-prev-10',
    patientId: 'pat-10',
    patientNom: 'Kenza Mansour',
    date: '2026-09-25',
    startTime: '10:00',
    endTime: '10:45',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
  },
  {
    id: 'ses-prev-11',
    patientId: 'pat-11',
    patientNom: 'Omar Sellami',
    date: '2026-09-25',
    startTime: '14:00',
    endTime: '14:45',
    durationMinutes: 45,
    isConventionne: false,
    status: 'realisee',
    tarif: 50,
  },
  {
    id: 'ses-prev-12',
    patientId: 'pat-12',
    patientNom: 'Mariem Jaziri',
    date: '2026-09-26',
    startTime: '10:00',
    endTime: '10:45',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
  },
  // Semaine du 14 au 19 Septembre 2026
  {
    id: 'ses-hist-1',
    patientId: 'pat-1',
    patientNom: 'Amine Ben Salem',
    date: '2026-09-14',
    startTime: '08:30',
    endTime: '09:15',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
  },
  {
    id: 'ses-hist-2',
    patientId: 'pat-2',
    patientNom: 'Yasmine Trabelsi',
    date: '2026-09-15',
    startTime: '09:15',
    endTime: '10:00',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
  },
  {
    id: 'ses-hist-3',
    patientId: 'pat-3',
    patientNom: 'Rayan Chahed',
    date: '2026-09-15',
    startTime: '10:45',
    endTime: '11:30',
    durationMinutes: 45,
    isConventionne: false,
    status: 'realisee',
    tarif: 50,
  },
  {
    id: 'ses-hist-4',
    patientId: 'pat-4',
    patientNom: 'Nour Bouazizi',
    date: '2026-09-16',
    startTime: '14:00',
    endTime: '14:45',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
  },
  {
    id: 'ses-hist-5',
    patientId: 'pat-5',
    patientNom: 'Mohamed Aziz Khemir',
    date: '2026-09-17',
    startTime: '08:30',
    endTime: '09:15',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
  },
  {
    id: 'ses-hist-6',
    patientId: 'pat-6',
    patientNom: 'Eya Mezghani',
    date: '2026-09-18',
    startTime: '15:30',
    endTime: '16:15',
    durationMinutes: 45,
    isConventionne: false,
    status: 'realisee',
    tarif: 50,
  },
  {
    id: 'ses-hist-7',
    patientId: 'pat-11',
    patientNom: 'Omar Sellami',
    date: '2026-09-18',
    startTime: '14:00',
    endTime: '14:45',
    durationMinutes: 45,
    isConventionne: false,
    status: 'annulee',
    tarif: 50,
    notesSeance: 'Annulée avec préavis 48h.',
  },
  {
    id: 'ses-hist-8',
    patientId: 'pat-7',
    patientNom: 'Khalil Dridi',
    date: '2026-09-19',
    startTime: '09:15',
    endTime: '10:00',
    durationMinutes: 45,
    isConventionne: true,
    status: 'realisee',
    tarif: 35,
  },
];
